from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from types import MappingProxyType
from typing import Any, Mapping


class MemoryErrorCode(StrEnum):
    """Stable machine-readable v0.7 domain error codes."""

    OCCURRENCE_MUTATION_FORBIDDEN = "OCCURRENCE_MUTATION_FORBIDDEN"
    MEMORY_UNKNOWN_SOURCE = "MEMORY_UNKNOWN_SOURCE"
    MEMORY_KNOWLEDGE_LEAK = "MEMORY_KNOWLEDGE_LEAK"
    MEMORY_INVALID_TRANSITION = "MEMORY_INVALID_TRANSITION"
    MEMORY_LINEAGE_CYCLE = "MEMORY_LINEAGE_CYCLE"
    RECORD_SCHEMA_INCOMPLETE = "RECORD_SCHEMA_INCOMPLETE"
    RECORD_PERMISSION_EXCEEDED = "RECORD_PERMISSION_EXCEEDED"
    RECORD_ATTEMPTS_PAST_REWRITE = "RECORD_ATTEMPTS_PAST_REWRITE"
    RECORD_CONSENT_REQUIRED = "RECORD_CONSENT_REQUIRED"
    EVIDENCE_SELF_PROVING = "EVIDENCE_SELF_PROVING"
    EVIDENCE_SOURCE_FAMILY_DUPLICATE = "EVIDENCE_SOURCE_FAMILY_DUPLICATE"
    CONFLICT_UNSUPPORTED_TYPE = "CONFLICT_UNSUPPORTED_TYPE"
    CONFLICT_MITIGATION_REQUIRED = "CONFLICT_MITIGATION_REQUIRED"
    ACK_PARTIAL_COMMIT_FORBIDDEN = "ACK_PARTIAL_COMMIT_FORBIDDEN"
    SAVE_DIGEST_MISMATCH = "SAVE_DIGEST_MISMATCH"
    REPLAY_DIGEST_MISMATCH = "REPLAY_DIGEST_MISMATCH"
    LIVE_STATE_BOUND_EXCEEDED = "LIVE_STATE_BOUND_EXCEEDED"


@dataclass(frozen=True, slots=True)
class MemoryKernelError(Exception):
    code: MemoryErrorCode
    message: str
    details: Mapping[str, Any] = MappingProxyType({})

    def __str__(self) -> str:
        return f"{self.code}: {self.message}"
